### ISSUE TITLE
Add `summarize` function for datasets

### ISSUE THREAD

**Issue by fschueler** [emmalanguage/emma-lib#2]
Many algorithms need specific conditions to be fulfilled by datasets for the algorithms to be applicable to the data or to be able to chose between different implementations. One way of checking those is to compute the necessary statistics on a per-algorithm basis.

Instead, I suggest to add a `summarize` library function that computes common summary statistics, such as `mean`, `std`, `var`, `count`, etc. since this is also often a first step of analyzing a dataset.

One example for such a summary in Spark is shown [here](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/optim/WeightedLeastSquares.scala#L340).

As a first step I suggest a summarize function over `DataBag`s of our various `Point` representations. 
An example implementation can be found [here](https://github.com/fschueler/emma-lib/blob/linear_regression/emma-lib/src/main/scala/org/emmalanguage/lib/ml/stats/Summarize.scala).

I also see the opportunity for optimization there since in most scenarios we would probably only really need a subset of all summary fields and so a typical user might write something like this:

```Scala
val summary = Summarize(dataset)
val (mean, std) = (summary.mean, summary.std)
``` 

where in the end not all fields that are computed in the fold are actually used. Now this might be optimized automatically(?) or we could parameterize the summary, similar to [R's `summarize` function](https://www.rdocumentation.org/packages/Hmisc/versions/4.0-3/topics/summarize).
A similar functionality is provided by [Stata's `summarize` command](https://stats.idre.ucla.edu/stata/output/descriptive-statistics-using-the-summarize-command/).

If we add single functions for `mean`, `std`, `var`, we should also enable to combine all those into one summary by passing them to the `summarize` function. The ideal design of the `summarize` library function(s) can be discussed here.

I labelled this as "starter" issue since I think it would be a good place for people to familiarize themselves with writing emma-lib functions. Ideally we would have summarize functions for the most common types of `DataBag`s. Maybe we can add a github label, too?

**Comment by aalexandrov** [comment]
I have a [WIP branch](https://github.com/aalexandrov/emma-lib/tree/stats) on that. So far I've implemented the following stats:

- `count`
- `sum`
- `min`
- `max`
- `mean`
- `variance` 
- `stddev`

Unfortunately I am still hitting bugs in the compiler while working on that, so I need to iterate on `emma` core simultaneously.

I suggest to merge this basic set and then create a follow-up issue for more elaborate statistics such as `approxDistinct` with `HyperLogLog`).

**Comment by fschueler** [comment]
Sounds good - I opened a PR from your branch ( #7 ) and hope that this is the most recent version?

**Comment by aalexandrov** [comment]
I am working on `stddev`, then I think we can merge this.
